### ISSUE TITLE
Links in field values

### ISSUE THREAD

**Issue by spacebeers** [gglukmann/use-google-sheets#36]
Hello. I've been using this hook for an app I'm building that uses a Google Sheet as the data source. It's been great to use and super easy to set up (specially compared to a lot of the other options out there) but I've got an issue where a column I need to view has a link in the data. 

<img width="395" alt="Screenshot 2023-03-17 at 08 57 18" src="https://user-images.githubusercontent.com/912954/225858634-922b957f-e684-49c3-b40a-91732ac4ebe6.png">

This is just returning as a flat string value like "TRK-FORD-13-433" rather than the actual contents of the cell I was expecting. 

If I'm just not doing something correctly then please let me know, otherwise is there a way around this?

Thanks

**Comment by gglukmann** [comment]
Hi, right now you can't get formatted values, only strings. So this is working as expected right now. Getting formatted values is possible, but this needs additional development for this library because formatted values have really complex object structure. Documentation can be found here https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values

**Comment by spacebeers** [comment]
Thanks for the reply. I'll have a look at the Google APIs which I was really trying to avoid.
